[package]
name = "rayla"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
description = "A ray tracing library and application framework."
repository = "https://github.com/qtf0x/rayla/"
keywords = ["ray-tracing", "3d"]
categories = ["game-development", "graphics", "multimedia", "multimedia::images", "rendering"]

[features]
single-precision = []

[dependencies]
